use std::str::FromStr;
use tapl::fullsimple::ast::{Term, Type};

grammar;

pub Term: Box<Term> = {
    "true" => Box::new(Term::True),
    "false" => Box::new(Term::False),
    "zero" => Box::new(Term::Zero),
    "succ(" <Term> ")" => Box::new(Term::Succ(<>)),
    "pred(" <Term> ")" => Box::new(Term::Pred(<>)),
    "iszero(" <Term> ")" => Box::new(Term::IsZero(<>)),
    "if" <Term> "then" <Term> "else" <Term> => Box::new(Term::If(<>)),
};
