[package]
name = "tapl"
version = "0.1.0"
authors = ["Amir Saeid <amir@glgdgt.com>"]

[dependencies]
nom = "3.2.0"

[[bin]]
name = "arith"
path = "src/bin/arith.rs"

[[bin]]
name = "tyarith"
path = "src/bin/tyarith.rs"

[[bin]]
name = "fulluntyped"
path = "src/bin/fulluntyped.rs"
